-- Q1. What are the details of all cars purchased in the year 2022?

SELECT c.*
	, s.sale_id
	, s.salesman_id
	, s.purchase_date
FROM
	sales s
    JOIN cars c
    ON s.car_id = c.car_id
WHERE
	YEAR(s.purchase_date) = 2022
ORDER BY
	s.purchase_date; 

-- Q2. What is the total number of cars sold by each salesperson?

SELECT s.salesman_id, sp.name
	, COUNT(s.sale_id) AS Cars_Sold
FROM
	sales s
    	JOIN salespersons sp
    	ON s.salesman_id = sp.salesman_id
GROUP BY
	s.salesman_id
    , sp.name; 

-- Q3. What is the total revenue generated by each salesperson?

SELECT s.salesman_id
	, sp.name
	, CONCAT("$", SUM(c.cost_$)) AS Total_revenue_generated
FROM
	sales s
    JOIN cars c
    ON s.car_id = c.car_id
    JOIN salespersons sp
    ON s.salesman_id = sp.salesman_id
GROUP BY
	s.salesman_id
    , sp.name; 
    
-- Q4. What are the details of the cars sold by each salesperson?

SELECT s.salesman_id
		, c.*
FROM
	sales s
    LEFT JOIN cars c
    ON s.car_id = c.car_id
ORDER BY
	s.salesman_id;

-- Q5. What is the total revenue generated by each car type?

SELECT c.*, CONCAT("$", count(s.car_id) * c.cost_$) AS Total_revenue_generated
FROM
	sales s
    LEFT JOIN cars c
    ON s.car_id = c.car_id
GROUP BY
	s.car_id;

-- Q6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

SELECT c.*
FROM
	sales s
    JOIN cars c
    ON s.car_id = c.car_id
    JOIN salespersons sp
    ON s.salesman_id = sp.salesman_id
WHERE
	sp.name = "Emily Wong"
    AND YEAR(s.purchase_date) = 2021;

-- Q7. What is the total revenue generated by the sales of hatchback cars?
    
SELECT CONCAT("$", (count(s.car_id) * c.cost_$)) AS Total_revenue_from_hatchback
FROM
	sales s
    JOIN cars c
    ON s.car_id = c.car_id
WHERE
	c.style = "Hatchback"
GROUP BY
	s.car_id;
    
-- Q8. What is the total revenue generated by the sales of SUV cars in the year 2022?

SELECT c.style
	, YEAR(s.purchase_date) AS year
    , CONCAT("$", SUM(c.cost_$)) AS Total_revenue_from_SUV_in_2022
FROM
	sales s
    JOIN cars c
    ON s.car_id = c.car_id
WHERE
	c.style = "SUV"
    AND YEAR(s.purchase_date) = 2022
GROUP BY
	c.style
    , YEAR(s.purchase_date);

-- Q9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

SELECT s.salesman_id, sp.name, sp.city, COUNT(s.sale_id) AS Count_of_cars_sold
FROM
	sales s
    JOIN salespersons sp
    ON s.salesman_id = sp.salesman_id
WHERE
	YEAR(s.purchase_date) = 2023
GROUP BY
	s.salesman_id
    , sp.name
    , sp.city
ORDER BY
	COUNT(s.sale_id) DESC
LIMIT 1;

-- Q10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

SELECT s.salesman_id
	, sp.name
    , sp.city
    , SUM(c.cost_$) AS Highest_revenue_generated
FROM
	sales s
    JOIN salespersons sp
    ON s.salesman_id = sp.salesman_id
    JOIN cars c
    ON s.car_id = c.car_id
WHERE
	YEAR(s.purchase_date) = 2022
GROUP BY
	s.salesman_id
    , sp.name
    , sp.city
ORDER BY
	SUM(c.cost_$) DESC
LIMIT 1; 
